'use client';

import { useState } from 'react';
import { supabase } from '@/lib/supabase';

type BusinessAssetState={id:string;avatar_url:string|null;header_url:string|null};

export default function BusinessBrandAssets({business,onChange}:{business:BusinessAssetState;onChange:(next:BusinessAssetState)=>void}){
 const[uploading,setUploading]=useState<'avatar'|'header'|null>(null);const[error,setError]=useState('');
 const logo=business.avatar_url?.startsWith('storage:')?`/api/assets?businessId=${business.id}&kind=avatar`:business.avatar_url||'';
 const background=business.header_url?.startsWith('storage:')?`/api/assets?businessId=${business.id}&kind=header`:business.header_url||'';
 const upload=async(file:File,kind:'avatar'|'header')=>{setUploading(kind);setError('');try{const{data:s}=await supabase.auth.getSession();const token=s.session?.access_token;if(!token)throw new Error('Session expired. Please sign in again.');const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};const prep=await fetch('/api/assets',{method:'POST',headers,body:JSON.stringify({action:'prepare',kind,contentType:file.type,size:file.size})});const p=await prep.json();if(!prep.ok)throw new Error(p.error||'Could not prepare image upload');const{error:uploadError}=await supabase.storage.from(p.bucket).uploadToSignedUrl(p.path,p.token,file,{contentType:file.type,cacheControl:'3600'});if(uploadError)throw uploadError;const complete=await fetch('/api/assets',{method:'POST',headers,body:JSON.stringify({action:'complete',kind,path:p.path})});const c=await complete.json();if(!complete.ok)throw new Error(c.error||'Could not save image');onChange({...business,[kind==='avatar'?'avatar_url':'header_url']:c.reference});}catch(caught){setError(caught instanceof Error?caught.message:'Image upload failed')}finally{setUploading(null)}};
 return <div className="rounded-[24px] border border-black/8 bg-white/75 p-4"><div><strong className="text-sm">Brand images</strong><p className="mt-1 text-xs leading-5 text-black/40">Your logo sits over the background image on the public profile.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-[150px_1fr]"><label className="cursor-pointer rounded-[20px] bg-[#F5F3ED] p-3"><input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,'avatar');e.target.value=''}}/><span className="text-[9px] font-bold uppercase tracking-[.12em] text-black/35">Logo</span><div className="mt-3 grid h-20 w-20 place-items-center overflow-hidden rounded-[22px] bg-white shadow-sm">{logo?<img src={logo} alt="Business logo" className="h-full w-full object-cover"/>:<span className="text-xs text-black/30">Add logo</span>}</div><span className="mt-3 block text-[10px] font-semibold">{uploading==='avatar'?'Uploading…':'Change logo'}</span></label><label className="cursor-pointer rounded-[20px] bg-[#F5F3ED] p-3"><input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,'header');e.target.value=''}}/><span className="text-[9px] font-bold uppercase tracking-[.12em] text-black/35">Background image</span><div className="relative mt-3 h-28 overflow-hidden rounded-[18px] bg-[#DDD7CC]">{background?<img src={background} alt="Business background" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-xs text-black/30">Add background image</div>}<div className="absolute inset-0 bg-black/10"/></div><span className="mt-3 block text-[10px] font-semibold">{uploading==='header'?'Uploading…':'Change background'}</span></label></div>{error?<p className="mt-3 rounded-[14px] bg-[#F8AE9D]/55 p-3 text-xs">{error}</p>:null}</div>;
}
