'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase';

type Analytics={days:number;metrics:{views:number;uniqueVisitors:number;directions:number;menu:number;orders:number;clicks:number};topActions:{id:string;count:number}[];trafficSources:{source:string;count:number}[];trend:{date:string;views:number;clicks:number}[]};
const label=(id:string)=>({map:'Directions',menu:'Menu',order:'Order',book:'Booking',website:'Website',call:'Call',shop:'Shop','gift-cards':'Gift cards',catering:'Catering',events:'Events',careers:'Careers',email:'Email'} as Record<string,string>)[id]||id.replace(/-/g,' ').replace(/^./,x=>x.toUpperCase());
function Mark(){return <svg viewBox="0 0 100 100" width="27" height="27" aria-hidden="true"><circle cx="50" cy="50" r="48"/><circle cx="50" cy="50" r="21" fill="#F7F7F3"/><circle cx="50" cy="44" r="7.4"/><path d="M45.2 50.2h9.6l2.2 16.3H43z"/></svg>}

export default function AnalyticsPage(){
 const router=useRouter();const[days,setDays]=useState(30);const[data,setData]=useState<Analytics|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{void(async()=>{setLoading(true);setError('');const{data:s}=await supabase.auth.getSession();if(!s.session){router.replace('/login');return}const res=await fetch(`/api/analytics?days=${days}`,{headers:{Authorization:`Bearer ${s.session.access_token}`}});const json=await res.json().catch(()=>({error:'Could not load analytics'}));if(!res.ok){setError(json.error||'Could not load analytics');setData(null)}else setData(json);setLoading(false)})()},[days,router]);
 const m=data?.metrics;const maxTrend=Math.max(1,...(data?.trend||[]).map(x=>x.views));const maxAction=Math.max(1,...(data?.topActions||[]).map(x=>x.count));const maxSource=Math.max(1,...(data?.trafficSources||[]).map(x=>x.count));
 return <main className="min-h-screen bg-[#F5F3ED] text-[#111]" style={{fontFamily:'var(--font-poppins)'}}><header className="sticky top-0 z-30 border-b border-black/8 bg-[#F5F3ED]/90 backdrop-blur-2xl"><div className="mx-auto flex w-[min(94%,1240px)] items-center justify-between py-4"><Link href="/" className="flex items-center gap-2 font-bold tracking-[-.04em]"><Mark/>OpenStatus</Link><div className="flex gap-2"><Link href="/builder" className="rounded-full px-4 py-2.5 text-xs font-semibold">Edit page</Link><Link href="/dashboard" className="rounded-full bg-black px-4 py-2.5 text-xs font-bold text-white">Dashboard</Link></div></div></header><div className="mx-auto w-[min(94%,1240px)] py-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><span className="text-[9px] font-bold uppercase tracking-[.16em] text-black/35">BUSINESS ANALYTICS</span><h1 className="mt-2 text-5xl font-semibold tracking-[-.06em]">What customers do.</h1><p className="mt-2 text-sm text-black/45">See how your OpenStatus turns visits into real-world action.</p></div><div className="flex rounded-full bg-white/75 p-1 shadow-sm">{[7,30,90].map(n=><button key={n} onClick={()=>setDays(n)} className={`rounded-full px-5 py-2.5 text-xs font-bold ${days===n?'bg-black text-white':'text-black/40'}`}>{n} days</button>)}</div></div>
 {error?<div className="mt-7 rounded-[28px] border border-black/8 bg-[#FFF2C1] p-6"><strong>Analytics needs one more connection.</strong><p className="mt-2 text-sm text-black/55">{error}</p></div>:null}
 {loading?<div className="mt-7 rounded-[28px] bg-white/60 p-8 text-sm text-black/40">Loading analytics…</div>:data?<><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Unique visitors',m!.uniqueVisitors],['Page views',m!.views],['Directions',m!.directions],['Menu views',m!.menu],['Orders',m!.orders]].map(([name,value],i)=><div key={String(name)} className={`rounded-[26px] border border-black/8 p-5 ${i===0?'bg-[#C8FF62]/60':'bg-white/70'}`}><span className="text-[9px] font-bold uppercase tracking-[.13em] text-black/35">{name}</span><strong className="mt-5 block text-4xl font-semibold tracking-[-.06em]">{value}</strong></div>)}</div>
 <div className="mt-4 grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-[30px] border border-black/8 bg-white/70 p-6"><div className="flex justify-between"><div><span className="text-[9px] font-bold uppercase tracking-[.14em] text-black/35">TRAFFIC</span><h2 className="mt-1 text-2xl font-semibold tracking-[-.04em]">Page views</h2></div><span className="text-xs text-black/35">Last {days} days</span></div><div className="mt-8 flex h-56 items-end gap-1">{data.trend.length?data.trend.map(x=><div key={x.date} className="group relative flex h-full min-w-1 flex-1 items-end"><div className="w-full rounded-t-md bg-[#7C3AED]/85 transition hover:bg-[#6D28D9]" style={{height:`${Math.max(3,x.views/maxTrend*100)}%`}}/><span className="pointer-events-none absolute bottom-full left-1/2 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded-lg bg-[#111] px-2 py-1 text-[9px] text-white group-hover:block">{x.date}: {x.views}</span></div>):<div className="grid h-full w-full place-items-center text-sm text-black/30">No visits yet</div>}</div></section><section className="rounded-[30px] bg-[#7C3AED] p-6 text-white"><span className="text-[9px] font-bold uppercase tracking-[.14em] text-white/35">QUICK READ</span><strong className="mt-3 block text-4xl tracking-[-.06em]">{m!.clicks}</strong><span className="text-sm text-white/45">customer actions</span><div className="mt-8 border-t border-white/10 pt-5"><span className="text-[9px] uppercase tracking-[.12em] text-white/35">Action rate</span><strong className="mt-2 block text-2xl">{m!.views?Math.round(m!.clicks/m!.views*100):0}%</strong><p className="mt-2 text-xs leading-5 text-white/40">Actions divided by page views.</p></div></section></div>
 <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="rounded-[30px] border border-black/8 bg-white/70 p-6"><span className="text-[9px] font-bold uppercase tracking-[.14em] text-black/35">TOP ACTIONS</span><h2 className="mt-1 text-2xl font-semibold tracking-[-.04em]">What they came to do</h2><div className="mt-6 space-y-4">{data.topActions.length?data.topActions.map((x,i)=><div key={x.id}><div className="mb-2 flex justify-between text-xs"><strong>{i+1}. {label(x.id)}</strong><span className="text-black/40">{x.count}</span></div><div className="h-2 overflow-hidden rounded-full bg-black/5"><div className="h-full rounded-full bg-black" style={{width:`${x.count/maxAction*100}%`}}/></div></div>):<p className="text-sm text-black/35">No actions yet.</p>}</div></section><section className="rounded-[30px] border border-black/8 bg-[#CBD9FF]/45 p-6"><span className="text-[9px] font-bold uppercase tracking-[.14em] text-black/35">TRAFFIC SOURCES</span><h2 className="mt-1 text-2xl font-semibold tracking-[-.04em]">Where customers found you</h2><div className="mt-6 space-y-4">{data.trafficSources.length?data.trafficSources.map(x=><div key={x.source}><div className="mb-2 flex justify-between text-xs"><strong>{x.source}</strong><span className="text-black/40">{x.count}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/60"><div className="h-full rounded-full bg-black" style={{width:`${x.count/maxSource*100}%`}}/></div></div>):<p className="text-sm text-black/35">Traffic sources will appear after visits.</p>}</div></section></div></>:null}</div></main>;
}
