import Link from 'next/link';

const faqs=[
 ['How do I change my live status?','Open Dashboard and use Right Now. Temporary changes override your regular hours and expire automatically.'],
 ['How do I change my regular hours?','Open Dashboard, choose Regular hours, make your changes, then save.'],
 ['How do I add ordering, booking or gift cards?','Open the Page Builder, add the block you need, and paste the URL from the service you already use.'],
 ['How do I add social profiles?','In the Page Builder, add a social network, paste the profile URL, then publish your changes.'],
 ['Does OpenStatus replace my website?','No. Your website stays your full website. OpenStatus is the fast mobile front door customers reach from your bio, QR code or social profile.'],
 ['How do I cancel or change billing?','Billing controls will live in Settings. Until billing launches, contact support and we will help directly.'],
];
export default function Help(){return <main className="min-h-screen bg-[#F5F3FF] px-5 py-8 text-[#111]" style={{fontFamily:'var(--font-poppins)'}}><div className="mx-auto max-w-4xl"><nav className="flex items-center justify-between"><Link href="/" className="font-bold tracking-[-.04em]">OpenStatus</Link><Link href="/dashboard" className="rounded-full bg-white px-4 py-2 text-xs font-semibold">Dashboard</Link></nav><section className="py-20"><span className="text-[10px] font-bold uppercase tracking-[.16em] text-black/35">HELP CENTER</span><h1 className="mt-4 max-w-2xl text-5xl font-semibold tracking-[-.06em] md:text-7xl">Small business should not need a manual.</h1><p className="mt-5 max-w-xl text-base leading-7 text-black/50">Quick answers for getting your page live, keeping it accurate, and sending customers where they need to go.</p></section><section className="grid gap-3">{faqs.map(([q,a])=><details key={q} className="rounded-[24px] border border-black/8 bg-white/70 p-5"><summary className="cursor-pointer list-none font-semibold">{q}</summary><p className="mt-3 max-w-2xl text-sm leading-6 text-black/50">{a}</p></details>)}</section><section className="my-10 rounded-[30px] bg-black p-7 text-white"><span className="text-[10px] font-bold uppercase tracking-[.16em] text-white/40">STILL NEED HELP?</span><h2 className="mt-3 text-3xl font-semibold tracking-[-.05em]">Talk to a human.</h2><p className="mt-2 text-sm text-white/55">Email us and include your business name and OpenStatus link.</p><a href="mailto:info@openstatus.co" className="mt-5 inline-block rounded-full bg-white px-5 py-3 text-xs font-bold text-black">info@openstatus.co</a></section></div></main>}
